//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMM.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int Id { get; set; }
        public System.DateTime SessionStartTime { get; set; }
        public System.DateTime SessionEndTime { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Topic { get; set; }
        public string TeacherName { get; set; }
        public string Location { get; set; }
    }
}
