/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

/* INSERT STUDENTS */

delete from [Students];
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Charline', 'Godbert', '+86 363 809 7872', '96783 Mccormick Alley', '12/20/2017', 'cgodbert0@woothemes.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Mateo', 'Surgen', '+62 287 568 5173', '2891 Thierer Alley', '12/7/2017', 'msurgen1@last.fm');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Sheila', 'Guillerman', '+351 279 855 2614', '363 Shelley Junction', '10/27/2018', 'sguillerman2@tripadvisor.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Elsinore', 'Cargenven', '+63 746 175 7237', '8 Westerfield Court', '2/2/2018', 'ecargenven3@statcounter.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Esteban', 'Turford', '+86 534 237 4852', '6398 Knutson Street', '4/1/2018', 'eturford4@latimes.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Xymenes', 'Prothero', '+20 838 146 2708', '219 Moland Street', '11/26/2017', 'xprothero5@ft.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Portia', 'Varsey', '+86 520 131 5083', '676 Ilene Parkway', '2/20/2018', 'pvarsey6@desdev.cn');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Westleigh', 'Ceschi', '+33 282 658 8928', '7 Union Way', '9/1/2018', 'wceschi7@wikipedia.org');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Ilse', 'Gilhoolie', '+7 657 351 7619', '34269 Gerald Drive', '7/21/2018', 'igilhoolie8@newsvine.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Clayson', 'Vogl', '+234 322 140 1371', '001 Straubel Hill', '9/28/2018', 'cvogl9@w3.org');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Gian', 'Luscott', '+86 284 768 5288', '4055 Forest Run Pass', '4/1/2018', 'gluscotta@smh.com.au');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Juli', 'McLoughlin', '+63 395 649 8889', '51 Del Mar Lane', '1/30/2018', 'jmcloughlinb@epa.gov');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Waverley', 'Curdell', '+234 891 478 5141', '7400 Barby Way', '5/7/2018', 'wcurdellc@google.co.uk');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Evelyn', 'Ohlsen', '+86 587 181 6596', '7872 Blackbird Road', '4/25/2018', 'eohlsend@alexa.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Cassandra', 'Gutridge', '+55 592 938 1387', '02982 Hanson Junction', '10/14/2018', 'cgutridgee@unblog.fr');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Porter', 'Raft', '+63 881 832 4151', '0 Nevada Circle', '8/20/2018', 'praftf@cornell.edu');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Gordan', 'Canete', '+33 915 988 3420', '527 Crowley Park', '10/31/2018', 'gcaneteg@ox.ac.uk');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Tate', 'Petracci', '+81 423 308 7091', '684 5th Plaza', '9/2/2018', 'tpetraccih@smh.com.au');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Thorvald', 'Ferres', '+36 608 675 1071', '361 Randy Circle', '10/17/2018', 'tferresi@google.de');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Kimble', 'Whimpenny', '+86 654 139 6390', '1 Fisk Lane', '11/5/2018', 'kwhimpennyj@last.fm');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Leann', 'Tristram', '+51 899 495 2744', '54 Thackeray Terrace', '10/31/2018', 'ltristramk@usa.gov');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Dolph', 'Goodbar', '+420 791 933 2994', '46 1st Park', '10/22/2018', 'dgoodbarl@stumbleupon.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Julina', 'Northin', '+54 693 359 8593', '2993 Vahlen Plaza', '3/14/2018', 'jnorthinm@yellowbook.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Junia', 'Juschke', '+351 991 690 6138', '1310 Morrow Court', '10/26/2018', 'jjuschken@intel.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Alex', 'Mila', '+62 788 968 7138', '97 Darwin Parkway', '4/17/2018', 'amilao@illinois.edu');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Paule', 'Joyes', '+86 306 505 7824', '88309 Bartillon Road', '2/19/2018', 'pjoyesp@elpais.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Ernst', 'Simonsson', '+7 235 982 9501', '1758 Raven Street', '7/18/2018', 'esimonssonq@usatoday.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Joanne', 'Belt', '+27 521 103 4141', '22024 Talisman Pass', '9/1/2018', 'jbeltr@senate.gov');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Genna', 'Critchard', '+86 365 134 1798', '7602 Colorado Trail', '4/2/2018', 'gcritchards@jiathis.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Dar', 'Steely', '+57 648 234 5850', '085 Rockefeller Park', '12/4/2017', 'dsteelyt@istockphoto.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Tamara', 'Renol', '+51 446 877 5043', '29586 Kinsman Way', '1/22/2018', 'trenolu@netlog.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Oates', 'Cobon', '+7 991 624 1645', '27278 Dahle Pass', '9/21/2018', 'ocobonv@about.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Dale', 'de Juares', '+55 712 445 0316', '14133 Emmet Way', '8/27/2018', 'ddejuaresw@vistaprint.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Gavra', 'Abbe', '+86 308 344 2685', '22543 Corscot Road', '12/23/2017', 'gabbex@columbia.edu');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Yankee', 'Ezzle', '+33 296 412 5686', '7 Maryland Point', '10/29/2018', 'yezzley@kickstarter.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Gill', 'Skayman', '+48 747 719 5245', '47 Green Ridge Road', '11/28/2017', 'gskaymanz@squarespace.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Eric', 'Lodewick', '+66 899 579 6727', '7773 Pankratz Alley', '4/5/2018', 'elodewick10@goo.gl');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Kassey', 'McParlin', '+55 162 749 6564', '24 Muir Plaza', '9/9/2018', 'kmcparlin11@eventbrite.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Locke', 'Ruske', '+52 327 847 7132', '1322 Barnett Terrace', '12/16/2017', 'lruske12@e-recht24.de');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Igor', 'Sirett', '+86 780 422 7279', '9 Village Pass', '10/18/2018', 'isirett13@last.fm');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Hermione', 'Lashley', '+7 812 199 4318', '382 Di Loreto Circle', '11/24/2017', 'hlashley14@mayoclinic.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Terese', 'Sommerlie', '+234 729 506 3561', '0263 Forest Run Plaza', '3/26/2018', 'tsommerlie15@ebay.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Ilyssa', 'Stockle', '+86 795 543 7721', '32 Ridgeview Avenue', '7/19/2018', 'istockle16@reverbnation.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Cristie', 'Langforth', '+86 734 378 3237', '83 Old Gate Court', '2/19/2018', 'clangforth17@fda.gov');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Odelinda', 'Whyteman', '+63 719 388 3611', '156 3rd Park', '10/3/2018', 'owhyteman18@prlog.org');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Thomasin', 'Alcorn', '+86 785 685 9543', '64 Talmadge Pass', '11/3/2018', 'talcorn19@stanford.edu');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Nap', 'Wiggin', '+86 574 519 7036', '00121 Merchant Drive', '8/19/2018', 'nwiggin1a@ted.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Becka', 'Padbury', '+86 850 968 6054', '77725 Main Drive', '3/19/2018', 'bpadbury1b@deviantart.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Adrianna', 'Siman', '+86 206 888 4305', '67 Acker Court', '4/26/2018', 'asiman1c@jiathis.com');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Christabel', 'Scranney', '+86 136 214 6280', '655 Delaware Park', '6/18/2018', 'cscranney1d@ed.gov');
insert into Students (FirstName, LastName, PhoneNumber, [Address], DateOfBirth, Email) values ('Dianne', 'Antonsen', '+1 815 344 7878', '9236 Blue Bill Park Parkway', '11/12/2018', 'dantonsen1e@si.edu');

/* INSERT SESSIONS */
delete from [Sessions];
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2018-12-24 15:50:57', '2018-12-16 08:20:11', 'International Business Machines Corporation', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', 'Orton Giacoboni', '37 Bartillon Crossing');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-11-15 19:56:33', '2019-04-04 15:40:35', 'Avinger, Inc.', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Alfonso Enderson', '60208 Pine View Crossing');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-10-12 11:20:37', '2019-08-30 21:25:35', 'Cott Corporation', 'Vestibulum ac est lacinia nisi venenatis tristique.', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.', 'Rica Revington', '28 Vera Parkway');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-06-20 17:10:39', '2019-01-06 14:14:58', 'Adient plc', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Gabriellia Benns', '0 Welch Pass');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-02-11 22:22:24', '2019-08-15 23:47:51', 'NBT Bancorp Inc.', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 'Waylen Turfitt', '521 Crowley Avenue');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-02-24 11:56:09', '2019-09-21 22:43:14', 'Exxon Mobil Corporation', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Isacco Hablot', '5 Londonderry Way');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-08-12 07:35:29', '2019-03-14 01:22:04', 'Hunter Maritime Acquisition Corp.', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Ky Booton', '7 Hoffman Crossing');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-03-27 16:24:29', '2019-10-13 03:42:16', 'AmeriServ Financial Inc.', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', 'Lou Geipel', '02143 Comanche Park');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-09-11 12:44:37', '2019-05-11 18:16:25', 'Chanticleer Holdings, Inc.', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Sheffield Wank', '571 Mccormick Crossing');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-05-01 20:03:12', '2019-09-28 02:09:08', 'Dynasil Corporation of America', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'Elyse Haster', '1 Kinsman Plaza');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-09-08 08:55:46', '2018-12-13 08:10:28', 'Telephone and Data Systems, Inc.', 'Aliquam non mauris.', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'Rip Krollman', '84 3rd Park');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-03-30 11:50:10', '2019-01-26 06:12:24', 'Digi International Inc.', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'Robinetta Shevill', '1 Nelson Drive');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-09-04 06:33:11', '2019-02-28 14:38:09', 'PIMCO Municipal Income Fund', 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Hewie Chrisp', '01 Susan Drive');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2018-11-30 08:59:17', '2019-03-23 13:16:29', 'Adamis Pharmaceuticals Corporation', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 'Karena Quest', '86879 Magdeline Place');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-10-13 19:26:35', '2019-08-22 15:35:57', 'Ashford Hospitality Prime, Inc.', 'In blandit ultrices enim.', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 'Sibelle Bielfeldt', '5749 Scoville Terrace');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-01-04 02:39:50', '2019-08-01 02:20:22', 'Paragon Commercial Corporation', 'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.', 'Glenden Alsopp', '442 Anhalt Plaza');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-01-31 08:14:39', '2019-07-12 10:05:53', 'Urban Edge Properties', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Elna Fullicks', '9 Jay Road');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-05-08 19:56:01', '2019-07-11 21:55:11', 'Dupont Fabros Technology, Inc.', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', 'Alyosha Cussen', '415 4th Junction');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-02-20 15:24:51', '2019-02-04 18:06:32', 'CoreLogic, Inc.', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'Anni Wistance', '76707 Goodland Road');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-03-01 03:53:01', '2019-10-08 23:23:10', 'Bioptix, Inc', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Cris Beakes', '7227 Sunnyside Terrace');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2018-12-03 00:20:04', '2019-06-22 06:01:57', 'Automatic Data Processing, Inc.', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'Etiam justo.', 'Hillery Callcott', '7006 High Crossing Court');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-07-30 00:16:50', '2019-08-24 09:10:08', 'Cyanotech Corporation', 'Integer a nibh. In quis justo.', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Brett Atton', '8 Oakridge Crossing');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2018-12-11 07:20:18', '2018-12-02 14:57:44', 'Goldman Sachs Group, Inc. (The)', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 'Jami Fosse', '44 Green Ridge Terrace');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-05-08 00:53:11', '2019-09-11 19:11:24', 'CHS Inc', 'In sagittis dui vel nisl. Duis ac nibh.', 'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Cece Flux', '15887 Jackson Circle');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-01-11 19:07:32', '2019-10-15 14:49:08', 'Axis Capital Holdings Limited', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', 'Forster de Savery', '86302 Mariners Cove Hill');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-02-20 08:41:47', '2018-12-08 02:27:48', 'Micron Technology, Inc.', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', 'Vernice Fussen', '79 Porter Parkway');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-09-26 03:58:26', '2019-02-18 09:12:40', 'FIRST REPUBLIC BANK', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Mahalia Spurrior', '213 Sage Place');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2018-12-18 10:30:48', '2019-09-11 14:12:40', 'Electronic Arts Inc.', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 'Emili Pallasch', '0 Vahlen Park');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-11-13 01:01:37', '2018-11-23 04:29:17', 'TG Therapeutics, Inc.', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 'Miguelita Showte', '644 Old Gate Road');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-01-12 14:20:42', '2019-11-08 13:51:39', 'Gemphire Therapeutics Inc.', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Salaidh Blincowe', '103 Sachs Point');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-07-26 16:00:57', '2019-07-22 03:22:47', 'BlackRock Utility and Infrastructure Trust', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 'Steffane Querrard', '612 Lawn Center');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-09-22 11:25:12', '2019-02-07 04:15:20', 'Becton, Dickinson and Company', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Gerhard Dunseath', '70946 Farmco Hill');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-09-14 12:28:14', '2019-03-16 06:39:05', 'Jason Industries, Inc.', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 'Sue Archdeacon', '19378 Lotheville Terrace');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-09-23 16:16:31', '2019-09-22 13:48:38', 'Axar Acquisition Corp.', 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'Integer ac leo. Pellentesque ultrices mattis odio.', 'Deb Aylen', '11223 Sullivan Road');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2018-12-27 12:46:48', '2019-06-25 18:40:46', 'Tekla Healthcare Opportunies Fund', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 'Ansel Umpleby', '9570 Memorial Place');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-02-10 04:32:20', '2019-06-14 21:32:20', 'Cimarex Energy Co', 'Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Corbie Cordy', '14011 Fisk Pass');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-08-30 23:48:27', '2019-07-19 07:03:28', 'NextEra Energy, Inc.', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 'Carmelita Johanssen', '655 Iowa Court');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-05-15 23:09:59', '2019-09-15 01:52:17', 'Federal Agricultural Mortgage Corporation', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 'Wyndham Boultwood', '56 Moose Crossing');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2018-12-10 03:38:05', '2019-06-21 07:34:21', 'Esterline Technologies Corporation', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', 'Lothaire Masson', '7739 Golf Course Trail');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-07-27 00:25:20', '2019-07-16 08:59:04', 'Biostar Pharmaceuticals, Inc.', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', 'Giles Pasterfield', '30 Tomscot Crossing');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-05-26 21:58:38', '2019-01-06 07:20:44', 'Methode Electronics, Inc.', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 'Mattias Lisimore', '76559 Pierstorff Park');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-10-29 10:17:44', '2019-05-16 21:29:31', 'NCS Multistage Holdings, Inc.', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 'Jules Kay', '78 Ridgeview Street');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-10-07 08:49:07', '2019-01-12 07:46:38', 'iShares MSCI Europe Financials Sector Index Fund', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.', 'Dasha Housego', '745 Forest Run Place');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-08-28 09:46:53', '2019-03-12 23:24:16', 'CU Bancorp (CA)', 'Phasellus in felis.', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 'Sharity Klugel', '72556 Ridgeway Junction');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-01-02 19:15:51', '2019-01-20 18:02:59', 'BOK Financial Corporation', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 'Aliquam erat volutpat.', 'Ninon McCleary', '3 Trailsway Place');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-02-08 07:00:25', '2019-08-26 19:17:51', 'Pacific Drilling S.A.', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Kalle Paolino', '1 Welch Road');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-08-27 19:32:39', '2019-07-04 14:46:10', 'Copa Holdings, S.A.', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'Pierette MacGinlay', '0 Meadow Valley Hill');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-11-18 05:23:55', '2019-05-30 19:50:57', 'CM Finance Inc', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 'Peder Marriner', '265 Porter Street');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-08-09 20:39:32', '2019-07-27 10:04:42', 'IntriCon Corporation', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', 'Jay Thorlby', '524 Michigan Crossing');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-10-04 07:29:43', '2018-12-21 10:31:00', 'First Trust MLP and Energy Income Fund', 'Nunc rhoncus dui vel sem.', 'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.', 'Michail Colleer', '78445 Claremont Pass');
insert into [Sessions] (SessionStartTime, SessionEndTime,  [Name], [Description], Topic, TeacherName,  [Location]) values ('2019-11-15 22:07:08', '2019-05-31 05:50:16', 'Genius Brands International, Inc.', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'Alanson Carrane', '88 Barby Center');
